codecov: 
 token: d40e3d75-a9f2-4e50-8210-0d57226b754c
 disable_default_path_fixes: no

coverage:
 precision: 2
 round: up
 range: "80...100"
 
 ignore:
  - "src/main/java/velcro/Controller"
  - "src/main/java/velcro/DrawingGUI.java"
  - "src/main/java/velcro/Obsolete"
  - "src/main/java/velcro/View"
